publishing {
    repositories {
        mavenLocal()
    }
    
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
            artifactId = project.artifact_name
            artifact tasks.named("sourceJar")
        }
    }
}

deployInator {
    versionEnvironmentVariableName = "VERSION"
    
    maven {
        publishTaskName = "publishMavenJavaPublicationToModmavenRepository"
    }
}